### ISSUE TITLE
Image resizes when mouse hovers over

### ISSUE THREAD

**Issue by joellti** [ryjjin/Obsidian-Dark-Graphite-Pie-theme#2]
Whenever the mouse hovers over any image it changes the size slightly and restores when it leaves the area. That becomes annoying when mouse is moving across Obsidian UI. With no custom theme this doesn't happen. Can you please disable this behavior? Thanks

**Comment by ryjjin** [comment]
Hey! I don't notice this behavior on my system, but it would definitely infuriate me - so I'll fix it)

Can you clarify:
- what is your operating system - windows, mac, linux?
- what version of obsidian?
- is the bug reproduced at any screen resolution? (in case you use multiple monitors with different resolutions)
- the bug is reproduced if at least one note is open, or you need to open several (if several - then from how many and how the panels are located)?

**Comment by joellti** [comment]
Windows 10 Pro build 21359
Obsidian 0.11.5
I'm using the built-in monitor of my notebook which is at 1080P resolution
Reproducible with one note open

Just another piece of info in case it matters, the behavior also exists with Obsidian dark rmx by _ph that yours is based on.

**Comment by ryjjin** [comment]
Sorry for the long reaction.
I was never able to reproduce the behavior on my devices, but I found the code that was responsible for scaling image sizes on hover. Please check if it works for you and let me know.

To update the behavior, do the following:
1. If you have been using Obsidian for a long time and found the times when the theme was written to the obsidian.css file in the root of the repository - delete these file (apparently, Obsidian applies settings first from it, and then from newer files from .obsidian/themes)
2. In Appearance settings click the button "reload themes" (button in the form of two rotating arrows) or choose the theme from community themes browser.

The changes should take effect immediately, but if they don't, try restarting Obsidian
